apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: daskclusters.kubernetes.dask.org
spec:
  scope: Namespaced
  group: kubernetes.dask.org
  names:
    kind: DaskCluster
    plural: daskclusters
    singular: daskcluster
    shortNames:
      - daskcluster
      - dsk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  description: Dask container image
                scheduler:
                  type: object
                  description: Dask scheduler information 
                replicas:
                  type: integer
                  description: Number of pods/workers in the worker group
                resources:
                  type: object
                  description: Resources for workers
                env:
                  type: object
                  description: Environment variables
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas